### ISSUE TITLE
Migrate docker image to quay

### ISSUE THREAD

**Issue by RiRa12621** [webdevops/pagerduty-exporter#11]
With docker announcing [rate limits](https://docs.docker.com/docker-hub/download-rate-limit/) it is a logical move to migrate images over to a different image registry.
Quay is a possible option, since it offers automated builds similar to the one currently used.

**Comment by mblaschke** [comment]
Hm.. would it make sense to build/push via github actions? Never used them so far.

**Comment by RiRa12621** [comment]
It's possible.
It is also a tiny bit more transparent what's happening that using quay native builders.
End of the day it depends a bit if you trust GitHub more with your quay secrets or quay with a GitHub token.

**Comment by mblaschke** [comment]
The image maybe should be pushed to Docker hub and Quay so the build via Github Action would be nice.
But this should then be done for all images in this project. Will take a while, have some vacation soon so i will have some time to play around :)

**Comment by RiRa12621** [comment]
Cool, let me know if you need any help.
Basically it should be similar to #14 but adding a step that pushes to the registry when an actual push to master happens
probably like below
```
name: Docker Image Push

on:
  push:
    branches:
      - master

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webdevops/pagerduty-exporter:$(date +%s)
    - name: Push to Quay
      run: docker push <something>
```
